name: Build AppImage

on:
  push:
    branches:
      - trunk
  schedule:
    - cron: '0 16 * * 5' # what could go wrong on a friday evening ¯\_ (ツ)_/¯
  workflow_dispatch:

jobs:
  check-new-release:
    runs-on: ubuntu-24.04
    outputs:
      SHOULD_BUILD: ${{ steps.get-release.outputs.SHOULD_BUILD }}
      CURRENT_VERSION: ${{ steps.get-release.outputs.CURRENT_VERSION }}
      LATEST_VERSION: ${{ steps.get-release.outputs.LATEST_VERSION }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Get Luanti's latest release version
        id: get-release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/luanti-org/luanti/releases/latest | jq -r .tag_name)
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV

          if [ -f current_version.txt ]; then
            CURRENT_VERSION=$(cat current_version.txt)
          else
            CURRENT_VERSION=""
          fi

          echo "Current version: ${CURRENT_VERSION}"
          echo "Latest version: ${LATEST_VERSION}"

          if [[ "$LATEST_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
              echo "Will make a build"
              echo "SHOULD_BUILD=true" >> $GITHUB_OUTPUT
              echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_OUTPUT
              echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
            else
              echo "No new release found."
              echo "SHOULD_BUILD=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "Latest version is not a semantic version, skipping build."
            echo "SHOULD_BUILD=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-24.04
    needs: check-new-release
    if: "${{ needs.check-new-release.outputs.SHOULD_BUILD == 'true' }}"
    permissions:
      contents: write
    env:
      LATEST_VERSION: ${{ needs.check-new-release.outputs.LATEST_VERSION }}
      CURRENT_VERSION: ${{ needs.check-new-release.outputs.CURRENT_VERSION }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Build AppImage
        run: docker compose up --build --abort-on-container-exit

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luanti-${{ env.LATEST_VERSION }}
          path: output/Luanti-${{ env.LATEST_VERSION }}.AppImage

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_VERSION }}
          files: output/Luanti-${{ env.LATEST_VERSION }}.AppImage
          body: |
            See https://github.com/luanti-org/luanti/compare/${{ env.CURRENT_VERSION }}...${{ env.LATEST_VERSION }} for full diff, or visit https://docs.luanti.org/about/changelog/ for a brief summary.

      - name: Update version file
        run: echo "${{ env.LATEST_VERSION }}" > current_version.txt

      - name: Commit version file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: current_version.txt
          commit_message: 'chore: update to ${{ env.LATEST_VERSION }}'
